version: '3.9'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - project

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - project
    depends_on:
      - mariadb
    
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    hostname: localhost
    restart: always
    depends_on: 
      - wordpress 
    ports: [ 443:443 ]
    volumes: 
      - wp:/var/www/html/wordpress
    networks: 
      - project
      
volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/fuserwyn/data/wp
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/fuserwyn/data/wp
      
networks:
  project:
    driver: bridge