CREATE DATABASE wordpress;
CREATE USER 'fuserwyn'@'%' IDENTIFIED BY '123123';
GRANT ALL PRIVILEGES ON wordpress.* TO 'fuserwyn'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123123';