CREATE DATABASE wordpress;
CREATE USER 'fuserwyn'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVELIGES ON wordpress.* TO 'fuserwyn'@'%';
FLUSH PRIVELIGES
ALTER USER 'root'@'localhst' IDENTIFIED BY 'root123123' 